# 使用官方的 Python 3.11 slim 镜像作为基础环境
image: python:3.11-slim

# 定义 CI/CD 的各个阶段
stages:
  - run

# 定义一个具体的作业（Job）
run_broadcast_job:
  stage: run
  
  # 在执行主脚本前需要运行的命令
  before_script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
  
  # 作业要执行的核心命令
  script:
    - echo "Running broadcast script..."
    - python main.py
  
  # 定义此作业何时运行
  rules:
    # 允许通过 GitLab UI 手动触发 ("Run pipeline")
    - if: '$CI_PIPELINE_SOURCE == "web"'
    # 允许通过计划任务触发 ("CI/CD Schedules")
    - if: '$CI_PIPELINE_SOURCE == "schedule"' 