# 运行参数
fetch_interval_minutes: 15

# K线数据源配置
kline:
  symbol: "BTCUSDT"
  interval: "1d"      # CoinGecko API 当前会忽略此参数，但保留以备将来使用
  limit: 90           # 获取过去90天的数据 (CoinGecko API 上限)

# 指标阈值
thresholds:
  sma30_multiplier:
    buy_large: 0.90
    buy_small: 1.00
    sell_small: 1.05
    sell_large: 1.10
  rsi:
    buy_large: 25
    buy_small: 40
    sell_small: 65
    sell_large: 75
  fear_index: # 恐惧贪婪
    buy_large: 30
  greed_index:
    sell_large: 75

# 飞书机器人
feishu:
  # webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/5c366e21-eec8-4688-9707-0c1237fed057"
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/c48647c0-d546-40e6-b358-c26d79db9068"
# 日志
log:
  path: "./logs/btc_broadcast.log"
  level: "INFO"
