name: Crypto Price Broadcast

on:
  workflow_dispatch: # 允许手动触发
  # schedule:
  #   # UTC 时间，"*/15 * * * *" 表示每15分钟执行一次
  #   - cron: "*/15 * * * *"

jobs:
  run-crypto-broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Crypto Broadcast
        env:
          GROQ_API_KEY_1: ${{ secrets.GROQ_API_KEY_1 }}
          GROQ_API_KEY_2: ${{ secrets.GROQ_API_KEY_2 }}
          GROQ_API_KEY_3: ${{ secrets.GROQ_API_KEY_3 }}
          CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
          MARKETAUX_API_TOKEN: ${{ secrets.MARKETAUX_API_TOKEN }} # 新增 Marketaux API Token
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        run: python main.py
