name: Crypto Price Broadcast

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # UTC 时间，"*/30 * * * *" 表示每30分钟执行一次
    - cron: "*/15 * * * *"

jobs:
  run-crypto-broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        env:
          # 此处引用了仓库的 Secrets，请确保在 GitHub -> Settings -> Secrets and variables -> Actions 中
          # 创建了一个名为 FEISHU_WEBHOOK_URL 的 Repository secret
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
        run: python main.py 